### ISSUE TITLE
Feature/Community page

### ISSUE THREAD

**Issue by Yooniverse42** [FRONTENDSCHOOL10/12Gain#10]
## 📄 설명

커뮤니티 페이지 및 컴포넌트 마크업

## 📋 TO-DO

- [ ] 커뮤니티 전체 페이지
- [ ] 커뮤니티 글쓰기 페이지
- [ ] 댓글 모달 or 페이지

## 🔔 기타

기타 사항을 적어주세요.
