### ISSUE TITLE
fix/kss

### ISSUE THREAD

**Issue by seungsu-K** [FRONTENDSCHOOL10/12Gain#104]
## 📄 설명

버그 수정

## 📋 TO-DO

- [ ] 모임 생성 뒤로가기
- [ ] 게시물 제목 스타일
- [ ] join Data 생성
- [ ] 채팅 데이터 없을 때 보내기 수정

## 🔔 기타

기타 사항을 적어주세요.
