### ISSUE TITLE
Feature/swiper 배너

### ISSUE THREAD

**Issue by Yooniverse42** [FRONTENDSCHOOL10/12Gain#49]
## 📄 설명

main 스와이퍼 배너 구현

## 📋 TO-DO

- [ ] 운동 관련 행사, 이벤트 swiper 제작
- [ ] 스와이퍼로 자동 슬라이드와 수동 제어 가능
- [ ] 배너 클릭 시 해당 이벤트/공지 상세 페이지로 이동

## 🔔 기타

기타 사항을 적어주세요.
