### ISSUE TITLE
Feature/community-button

### ISSUE THREAD

**Issue by Yooniverse42** [FRONTENDSCHOOL10/12Gain#53]
## 📄 설명

커뮤니티 페이지 및 버튼 스타일링

## 📋 TO-DO

- [ ] 커뮤니티 페이지 위치 이동
- [ ] 변경된 버튼 스타일 적용
- [ ] 클래스명 및 css 컨벤션 적용

## 🔔 기타

기타 사항을 적어주세요.
