### ISSUE TITLE
Feature/PostDetails 모임글 상세 페이지

### ISSUE THREAD

**Issue by seungsu-K** [FRONTENDSCHOOL10/12Gain#62]
## 📄 설명

모임글 클릭 시 랜더링되는 상세 페이지

## 📋 TO-DO

- [ ] 모임 글 데이터 받아와서 상세 페이지 정보 렌더링
- [ ] 참여하기 버튼 클릭 시 모임에 참가한 데이터가 추가되고 채팅하기 버튼으로 변경
- [ ] 채팅하기 버튼 클릭 시 채팅방으로 연결
